apiVersion: v2
dependencies:
- condition: mongodb.deploy
  name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 13.16.4
- condition: kafka.deploy
  name: kafka
  repository: https://charts.bitnami.com/bitnami
  version: 20.0.4
description: SD-Core 5G control plane services
icon: https://guide.opencord.org/logos/cord.svg
name: 5g-control-plane
version: 3.0.0
