# SPDX-FileCopyrightText: 2024-present Aether Project (Part of Linux Foundation) <dev@lists.aetherproject.org>
# SPDX-FileCopyrightText: 2021-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

# Default values for all SD-CORE Helm charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Images tagged for the release
omec-control-plane:
  enable4G: false
  #images:
  #  tags:
      #4G control Plane images
  #config:
  #  config4g:
  #    deploy: true

# Override values for omec-user-plane Helm Chart
# https://github.com/omec-project/sdcore-helm-charts/blob/main/bess-upf/values.yaml
omec-user-plane:
  enable: false

omec-sub-provision:
  enable: false
  # images:
  #   repository: "registry.aetherproject.org/proxy/"
    #tags:
    #  simapp: #add simapp override image

5g-ran-sim:
  enable: false
  #images:
  #  tags:
      #RAN SIM image
