{{/*
# Copyright 2024-present Intel Corporation
# Copyright 2020-present Open Networking Foundation

# SPDX-License-Identifier: Apache-2.0
*/}}
{{- if .Values.config.udm.deploy }}
# {{ tuple "udm" . | include "5g-control-plane.service_account" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udm
  labels:
{{ tuple "udm" . | include "5g-control-plane.metadata_labels" | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ tuple "udm" . | include "5g-control-plane.metadata_labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple "udm" . | include "5g-control-plane.metadata_labels" | indent 8 }}
    {{- with .Values.config.udm.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      serviceAccountName: udm-sa
    {{- if .Values.nodeSelectors.enabled }}
      nodeSelector:
        {{ .Values.nodeSelectors.label }}: {{ .Values.nodeSelectors.value }}
    {{- end }}
    {{- if hasKey .Values.images "pullSecrets" }}
      imagePullSecrets:
{{ toYaml .Values.images.pullSecrets | indent 8 }}
    {{- end }}
      initContainers:
      - name: wait-udm-module
        image: {{ .Values.images.repository }}{{ .Values.images.tags.init }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        command:
          - sh
          - -c
          - until nslookup udm; do echo waiting for udm; sleep 4; done;
      - name: wait-udr-module
        image: {{ .Values.images.repository }}{{ .Values.images.tags.init }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        command:
          - sh
          - -c
          - until nslookup udr; do echo waiting for udr; sleep 4; done;
    {{- if .Values.config.coreDump.enabled }}
    {{ tuple "udm" . | include "5g-control-plane.coredump_init" | indent 6 }}
    {{- end }}
      containers:
      - name: udm
        image: {{ .Values.images.repository }}{{ .Values.images.tags.udm }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
      {{- if .Values.config.coreDump.enabled }}
        securityContext:
          runAsUser: 0
      {{- end }}
        stdin: true
        tty: true
        command:
          - /opt/udm-run.sh
        env:
      {{- if eq .Values.config.GIN.mode "release" }}
        - name: GIN_MODE
          value: release
      {{- end }}
      {{- if .Values.config.udm.ssm.enable }}
        - name: SSM_SERVICE_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.config.udm.credentialsSecretName }}
              key: {{ .Values.config.udm.credentials.serviceIdKey | quote }}
        - name: SSM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.config.udm.credentialsSecretName }}
              key: {{ .Values.config.udm.credentials.passwordKey | quote }}
      {{- end }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      {{- if .Values.resources.enabled }}
        resources:
{{ toYaml .Values.resources.udm | indent 10 }}
      {{- end }}
        volumeMounts:
        - name: nf-config
          mountPath: /opt
        - name: certs
          mountPath: /var/run/certs
          readOnly: true
      {{- if .Values.config.udm.ssm.enable }}
        - name: udm-tls
          mountPath: /etc/udm/tls
          readOnly: true
      {{- end }}
      {{- if .Values.config.coreDump.enabled }}
        - name: coredump
          mountPath: /tmp/coredump
      {{- end }}
      volumes:
      - name: nf-config
        configMap:
          name: udm
          defaultMode: 493
      - name: certs
        secret:
          secretName: udm-certs
    {{- if .Values.config.udm.ssm.enable }}
      - name: udm-tls
        secret:
          secretName: {{ .Values.config.udm.tlsSecretName }}
          items:
            - key: {{ .Values.config.udm.tlsSecretKeys.cert | quote }}
              path: tls.crt
            - key: {{ .Values.config.udm.tlsSecretKeys.key | quote }}
              path: tls.key
            - key: {{ .Values.config.udm.tlsSecretKeys.ca | quote }}
              path: ca.crt
    {{- end }}
    {{- if .Values.config.coreDump.enabled }}
      - name: host-rootfs
        hostPath:
          path: /
      - name: coredump
        hostPath:
          path: {{ .Values.config.coreDump.path }}
    {{- end }}
{{- end }}
